/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'demhatre' at '8/3/17 3:31 PM' with Gradle 2.13
 *
 * @author demhatre, @date 8/3/17 3:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
